CREATE TABLE clinicaMedica_KZ.kz_empleados (
    idEmpleados INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50),
    apellidos VARCHAR(50),
    fecha_nacimiento DATE,
    celular VARCHAR(15),
    correo VARCHAR(50),
    genero VARCHAR(10),
    celular_emergencias VARCHAR(15),
    nombre_contacto_emergencia VARCHAR(100),
    estado_civil VARCHAR(10),
    conyugue VARCHAR(100),
    numero_hijos INT,
    nacionalidad VARCHAR(15),
    idiomas VARCHAR(50),
    nivel_certificcado VARCHAR(20),
    campo_estudio VARCHAR(30),
    escuela_superior VARCHAR(35),
    escuela_media VARCHAR(30),
    escuela VARCHAR(30),
    pais VARCHAR(30),
    departamento VARCHAR(30),
    direccion VARCHAR(250),
    celular_laboral VARCHAR(15),
    correo_laboral VARCHAR(30),
    area VARCHAR(30),
    jefe_inmediato VARCHAR(50),
    direccion_laboral VARCHAR(250),
    aprobador VARCHAR(50),
    fecha_ingreso DATE,
    salario FLOAT,
    puesto_laboral VARCHAR(30),
    PIN INT,
    contrasena VARCHAR(30),
    estado VARCHAR(8),
    imagen BLOB
);
